name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint and test
        env:
          CI: true
        run: |
         yarn --offline --frozen-lockfile --non-interactive
         yarn lint
         yarn static:build
         yarn test
         yarn static:serve -l 4000 &
         yarn test:e2e

